"""empty message

Revision ID: 73f1887e0496
Revises: 38b475ae7659
Create Date: 2022-05-13 09:18:19.479050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f1887e0496'
down_revision = '38b475ae7659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_interested_at_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'interested_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('interested_at', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_interested_at_fkey', 'user', 'animal', ['interested_at'], ['id'])
    # ### end Alembic commands ###
