"""empty message

Revision ID: 75a866510130
Revises: a10d3d208166
Create Date: 2022-05-20 17:20:10.004636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a866510130'
down_revision = 'a10d3d208166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('animal', 'is_interest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('is_interest', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('favorites')
    # ### end Alembic commands ###
