"""empty message

Revision ID: 764aa00522b7
Revises: 
Create Date: 2022-05-17 16:03:09.937487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764aa00522b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=80), nullable=True))
    op.drop_column('user', 'authenticated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
