"""empty message

Revision ID: a10d3d208166
Revises: 9be514203fe3
Create Date: 2022-05-19 13:00:20.571132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10d3d208166'
down_revision = '9be514203fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('is_interest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal', 'is_interest')
    # ### end Alembic commands ###
